# -*- coding: utf-8 -*-
"""Given a tuple with three elements (x, y, z), write a Python program to unpack the tuple and assign the values to three variables..ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Lzm0gQUR2XCZpAMNm8nKDmjDICYQ3gR
"""

# Given a tuple with three elements (x, y, z), write a Python program to unpack the tuple and assign the values to three variables.
t1=(1,2,3)
x=t1[0]
y=t1[1]
z=t1[2]
print(x,' ',y,' ',z)

# Given a tuple with three elements (x, y, z), write a Python program to unpack the tuple and assign the values to three variables.
my_tuple=(1,2,3)
# unpack_tuple
x,y,z=my_tuple
print('x:',x)
print('Y:',y)
print('Z:',z)

