# -*- coding: utf-8 -*-
"""Given a list of integers, write a Python program to create a new list that contains only the even numbers from the original list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_THq5f2qmLih-g4ZpULXH4OeteaRAWeY
"""

# Given a list of integers, write a Python program to create a new list that contains only the even numbers from the original list
a=[2,3,4,5,6,7,8,9,1,11,12,23,45]
b=[]
for i in a:
  if i%2==0:
    b.append(i)


print(b)

